services:
  nasaapp_php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./php-app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    networks:
      - nasaapp_network

  nasaapp_nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./php-app/public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - nasaapp_php
    networks:
      - nasaapp_network

  python-app:
    build:
      context: ./docker/python
    volumes:
      - ./python-app/:/app
      - ./docker/python/requirements.txt:/requirements.txt
    ports:
      - '4000:4000'
    restart: always

networks:
  nasaapp_network: