<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMMx6Xix\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMMx6Xix/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMMx6Xix.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMMx6Xix\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMMx6Xix\App_KernelDevDebugContainer([
    'container.build_hash' => 'MMx6Xix',
    'container.build_id' => 'e6d1902f',
    'container.build_time' => 1728119782,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMMx6Xix');
